(()=>{"use strict";
const $=id=>document.getElementById(id);const KEY="bellabeV4_1";const D={xp:0,coins:30,level:1,avatar:"🧑🏿‍🎓",badges:[],unlocked:["campus","mots"],completed:[],games:0,name:"Explorateur",draft:"",wardrobe:["🧢"],decor:["🛏️"],pet:"🐶",welcome:true};let S=load();
function load(){
  try{
    const old=JSON.parse(localStorage.getItem("bellabeV4")||"null");
    const cur=JSON.parse(localStorage.getItem(KEY)||"null");
    return {...D,...(old||{}),...(cur||{})};
  }catch(e){return {...D}}
}function save(){localStorage.setItem(KEY,JSON.stringify(S));stats()}
function stats(){$("xp").textContent=S.xp;$("coins").textContent=S.coins}
function toast(t){let e=document.getElementById("toast");e.textContent=t;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,1700)}
function reward(x,c=0,b=""){S.xp+=x;S.coins+=c;S.level=1+Math.floor(S.xp/200);if(b&&!S.badges.includes(b))S.badges.push(b);save();toast(`⭐ +${x} XP${c?` · 🪙 +${c}`:""}${b?` · 🏅 ${b}`:""}`)}
function go(p){scrollTo(0,0);({home,map,work,games,profile,mission,house}[p]||home)()}window.go=go;
function shell(t,b){$("screen").innerHTML=`<button class="back" onclick="go('home')">← Accueil</button><h2>${t}</h2>${b}`;stats()}
function home(){$("screen").innerHTML=`<section class="hero"><div class="twesy"><div class="face">🤖✨</div><div><h1>Bienvenue dans l'Aventure Scolaire de Bellabe Adssa Twesy !!!</h1><p>Dans la v4, ton monde, ta maison et tes récompenses évoluent avec toi.</p></div></div><button class="btn primary" onclick="go('mission')">🚀 Mission du jour</button></section><div class="grid"><button class="tile" onclick="go('map')"><span class="emoji">🗺️</span><b>Explorer</b><p>Découvre les zones</p></button><button class="tile" onclick="go('games')"><span class="emoji">🎮</span><b>Mini-jeux</b><p>Plusieurs défis</p></button><button class="tile" onclick="go('house')"><span class="emoji">🏠</span><b>Ma maison</b><p>Décore ton espace</p></button><button class="tile" onclick="go('work')"><span class="emoji">📝</span><b>Mon travail</b><p>Brouillon et impression</p></button></div><section class="card" style="padding:17px;margin-top:14px"><h3>🤖 Twesy</h3><p>« Chaque erreur est une piste pour apprendre. On essaie encore ? »</p></section>`;stats()}
const Z=[["campus","🏫","Grand Campus","Accueil"],["mots","📖","Forêt des Mots","Français"],["nombres","🔢","Vallée des Nombres","Mathématiques"],["science","🧪","Île des Découvertes","Sciences"],["savoir","🌍","Continent du Savoir","Histoire & géographie"],["creative","🎨","Île Créative","Création"],["enigmes","🗝️","Tour des Énigmes","Logique"],["castle","🏰","Château de Bellabe Adssa","Objectif final"]];
function map(){shell("🗺️ Carte interactive",`<p>Les zones se débloquent au fil de ton aventure.</p><div class="map">${Z.map(z=>{let o=S.unlocked.includes(z[0])||z[0]=="campus";return `<div class="zone ${o?"":"locked"}"><div class="zemoji">${z[1]}</div><div><b>${z[2]}</b><br><small>${z[3]}</small><br>${o?`<button class="btn secondary" onclick="explore('${z[0]}')">Explorer</button>`:"🔒 Verrouillée"}</div></div>`}).join("")}</div>`)}
window.explore=id=>{if(id==="mots"||id==="campus")mission();else shell("🌟 "+(Z.find(x=>x[0]===id)?.[2]||"Zone"),`<section class="card"><div class="big">${Z.find(x=>x[0]===id)?.[1]||"✨"}</div><p>De nouveaux défis arrivent dans cette zone.</p><button class="btn primary" onclick="go('games')">🎮 Faire un défi</button></section>`)}
function mission(){shell("📚 Mission — Le premier jour",`<section class="card"><p>Visite le campus en répondant à trois défis. Ta première grande récompense débloquera la Vallée des Nombres.</p><div id="mq"></div></section>`);let q=[["Où emprunte-t-on des livres ?","Bibliothèque",["Bibliothèque","Laboratoire","Stade"]],["7 + 5 = ?","12",["10","12","15"]],["La planète rouge est…","Mars",["Mars","Vénus","Jupiter"]]],i=0,s=0;function ask(){let x=q[i];$("mq").innerHTML=`<div class="question">${i+1}/3 — ${x[0]}</div><div class="answers">${x[2].map(a=>`<button class="answer" onclick="ans(${JSON.stringify(a)},${JSON.stringify(x[1])})">${a}</button>`).join("")}</div>`}window.ans=(a,c)=>{if(a===c){s++;toast("✅ Bonne réponse !")}else toast("💡 Continue, Twesy t'aide !");i++;if(i<q.length)setTimeout(ask,450);else setTimeout(()=>{$("mq").innerHTML=`<div class="reward">🎉 ${s}/3 réussites<br><button class="btn primary" onclick="completeMission()">Réclamer 50 XP + 20 pièces</button></div>`},450)};window.completeMission=()=>{if(!S.completed.includes("m1")){S.completed.push("m1");if(!S.unlocked.includes("nombres"))S.unlocked.push("nombres");reward(50,20,"Premier Pas")}go("map")};ask()}
function games(){shell("🎮 Mini-jeux",`<div class="grid"><button class="tile" onclick="numbers()"><span class="emoji">🔢</span><b>Course des Nombres</b><p>Calculs rapides</p></button><button class="tile" onclick="words()"><span class="emoji">🔤</span><b>Mot Mystère</b><p>Devine</p></button><button class="tile" onclick="detective()"><span class="emoji">🕵️</span><b>Détective</b><p>Indice logique</p></button><button class="tile" onclick="memory()"><span class="emoji">🧠</span><b>Mémoire</b><p>Retrouve les paires</p></button><button class="tile" onclick="science()"><span class="emoji">🧪</span><b>Laboratoire</b><p>Sciences</p></button><button class="tile" onclick="creative()"><span class="emoji">🎨</span><b>Créatif</b><p>Suites et logique</p></button></div>`)}
function done(){S.games++;reward(20,5);setTimeout(games,700)}
function numbers(){let a=2+Math.floor(Math.random()*9),b=2+Math.floor(Math.random()*9),mul=Math.random()<.5,ans=mul?a*b:a+b;shell("🔢 Course des Nombres",`<section class="card"><div class="big">${a} ${mul?"×":"+"} ${b} = ?</div><input id="v" class="input" type="number"><button class="btn primary" onclick="check(${ans})">Valider</button></section>`);window.check=n=>Number($("v").value)===n?(toast("🎉 Exact !"),done()):toast("💡 Essaie encore !")}
function words(){let q=[["🐶","CHIEN"],["📚","LIVRE"],["☀️","SOLEIL"],["🌳","ARBRE"]][Math.floor(Math.random()*4)];shell("🔤 Mot Mystère",`<section class="card"><div class="big">${q[0]}</div><input id="v" class="input" placeholder="Écris le mot"><button class="btn primary" onclick="check('${q[1]}')">Valider</button></section>`);window.check=a=>$("v").value.trim().toUpperCase()===a?(toast("🌟 Bravo !"),done()):toast("💡 Cherche encore.")}
function detective(){shell("🕵️ Détective",`<section class="card"><div class="question">Un livre a disparu. Quel indice est le plus utile ?</div><div class="answers"><button class="answer" onclick="d(true)">Une empreinte près de l'étagère</button><button class="answer" onclick="d(false)">La météo</button><button class="answer" onclick="d(false)">La couleur du mur</button></div></section>`);window.d=o=>o?(toast("🔎 Bon raisonnement !"),done()):toast("🤔 Cherche le lien avec le livre.")}
function memory(){let a=["🍎","⭐","🐶","🌈","🍎","⭐","🐶","🌈"].sort(()=>Math.random()-.5),first=null,lock=false,n=0;shell("🧠 Tour de la Mémoire",`<p>Retrouve les 4 paires.</p><div class="memory">${a.map((x,i)=>`<button class="mem" id="m${i}" onclick="flip(${i})">?</button>`).join("")}</div>`);window.flip=i=>{if(lock)return;let e=document.getElementById("m"+i);if(e.classList.contains("open"))return;e.textContent=a[i];e.classList.add("open");if(first===null)first=i;else if(a[first]===a[i]){n++;first=null;if(n===4)done()}else{lock=true;let j=first;first=null;setTimeout(()=>{[j,i].forEach(k=>{let q=document.getElementById("m"+k);q.textContent="?";q.classList.remove("open")});lock=false},600)}}}
function science(){let q=[["L'eau gèle à…","0 °C",["0 °C","50 °C","100 °C"]],["Quel organe sert principalement à respirer ?","Poumons",["Poumons","Cœur","Estomac"]]][Math.floor(Math.random()*2)];shell("🧪 Laboratoire",`<section class="card"><div class="question">${q[0]}</div><div class="answers">${q[2].map(a=>`<button class="answer" onclick="sci(${JSON.stringify(a)},${JSON.stringify(q[1])})">${a}</button>`).join("")}</div></section>`);window.sci=(a,c)=>a===c?(toast("🧪 Expérience réussie !"),done()):toast("💡 Observe la question.")}
function creative(){shell("🎨 Atelier Créatif",`<section class="card"><div class="question">Complète : ⭐ 🌙 ⭐ 🌙 ?</div><div class="answers"><button class="answer" onclick="cr(1)">⭐</button><button class="answer" onclick="cr(0)">🔥</button><button class="answer" onclick="cr(0)">🌈</button></div></section>`);window.cr=o=>o?(toast("🎨 Parfait !"),done()):toast("💡 La suite alterne deux symboles.")}
function house(){shell("🏠 Ma maison",`<section class="card"><div class="big">🏠</div><h3>Ma chambre</h3><p>Objets : ${S.decor.join(" ")} · Compagnon : ${S.pet}</p><h3>Décoration</h3><div class="shop">${["🛏️","📚","🪴","🖼️","🎮","🔬"].map(x=>`<button class="item" onclick="buyDecor('${x}')">${x}<br><small>10 🪙</small></button>`).join("")}</div><h3>🐾 Animal compagnon</h3><div class="shop">${["🐶","🐱","🐰","🐢","🐦"].map(x=>`<button class="item" onclick="pet('${x}')">${x}</button>`).join("")}</div></section>`);window.buyDecor=x=>{if(S.coins>=10&&!S.decor.includes(x)){S.coins-=10;S.decor.push(x);save();house();toast("🏠 Objet ajouté !")}else toast("🪙 Il faut 10 pièces.")};window.pet=x=>{S.pet=x;save();house();toast("🐾 Compagnon choisi !")}}
function work(){shell("📝 Mon Travail",`<section class="card"><p>Ton brouillon est sauvegardé sur cet appareil.</p><div id="draft" class="work" contenteditable="true">${S.draft.replaceAll("&","&amp;").replaceAll("<","&lt;")}</div><button class="btn success" onclick="saveDraft()">💾 Enregistrer</button><button class="btn secondary" onclick="download()">⬇️ Télécharger</button><button class="btn secondary" onclick="print()">🖨️ Imprimer / PDF</button></section><section class="card"><h3>🤖 Aide de Twesy</h3><button class="btn primary" onclick="toast('💡 Commence par souligner les mots importants de la consigne.')">Donner une piste</button></section>`);window.saveDraft=()=>{S.draft=$("draft").innerText;save();toast("💾 Sauvegardé !")};window.download=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([$("draft").innerText],{type:"text/plain"}));a.download="mon-travail.txt";a.click()}}
function profile(){shell("👤 Mon Profil",`<section class="card"><div class="avatar">${S.avatar}</div><h3>Niveau ${S.level} — ${S.name}</h3><p>⭐ ${S.xp} XP · 🪙 ${S.coins} · 🎮 ${S.games} parties</p><div class="progress"><i style="width:${S.xp%200/2}%"></i></div><h3>Avatar</h3><div class="avatars">${["🧑🏿‍🎓","👩🏾‍🔬","🧑🏽‍🚀","👨🏿‍🎨","🧑🏻‍🏫","👩🏽‍🚀"].map(x=>`<button class="av ${x===S.avatar?"sel":""}" onclick="av('${x}')">${x}</button>`).join("")}</div><h3>🏅 Badges</h3>${S.badges.map(x=>`<span class="badge">🏅 ${x}</span>`).join("")||"<p>Aucun badge pour le moment.</p>"}<p><button class="btn danger" onclick="reset()">Réinitialiser</button></p></section>`);window.av=x=>{S.avatar=x;save();profile()};window.reset=()=>{if(confirm("Réinitialiser ?")){localStorage.removeItem(KEY);S=load();home()}}}
stats();home();if(S.welcome){S.welcome=false;save();toast("🤖 Twesy : bienvenue dans la v4 !")}if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=42",{updateViaCache:"none"}).catch(()=>{});
})();