(()=>{"use strict";
const KEY="bellabeV3";
const defaults={xp:0,coins:20,level:1,avatar:"🧑🏿‍🎓",badges:[],completed:[],unlocked:["campus","mots"],games:0,name:"Explorateur",draft:"",welcome:true};
let S=load(), currentGame=null;
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch(e){return {...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(S));renderStats()}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,1800)}
function addXP(n){S.xp+=n;S.level=1+Math.floor(S.xp/200);save();toast("⭐ +"+n+" XP !")}
function reward(xp,coins=0,badge=""){addXP(xp);if(coins){S.coins+=coins;toast("🪙 +"+coins+" pièces !")}if(badge&&!S.badges.includes(badge)){S.badges.push(badge);toast("🏅 Badge débloqué : "+badge)}save()}
function renderStats(){document.getElementById("xp").textContent=S.xp;document.getElementById("coins").textContent=S.coins}
function go(page){currentGame=null;window.scrollTo(0,0);({home, map,work,games,profile,mission}[page]||home)()}
window.go=go;
function shell(title,body){document.getElementById("screen").innerHTML=`<button class="back" onclick="go('home')">← Accueil</button><h2>${title}</h2>${body}`;renderStats()}
function home(){document.getElementById("screen").innerHTML=`<section class="hero"><div class="twesy"><div class="face">🤖✨</div><div><h1>Bienvenue dans l'Aventure Scolaire de Bellabe Adssa Twesy !!!</h1><p>Apprends, joue, gagne des récompenses et explore ton univers.</p></div></div><button class="btn primary" onclick="go('map')">🗺️ Continuer l'aventure</button></section><div class="grid"><button class="tile" onclick="go('mission')"><span class="emoji">📚</span><b>Mission du jour</b><p>Le premier jour</p></button><button class="tile" onclick="go('games')"><span class="emoji">🎮</span><b>Mini-jeux</b><p>Apprendre en jouant</p></button><button class="tile" onclick="go('work')"><span class="emoji">📝</span><b>Mon travail</b><p>Écrire et sauvegarder</p></button><button class="tile" onclick="go('profile')"><span class="emoji">${S.avatar}</span><b>Mon profil</b><p>Niveau ${S.level}</p></button></div><section class="card"><h3>🤖 Message de Twesy</h3><p>« Je ne vais pas faire tes devoirs à ta place. Je vais t'aider à trouver la solution ! »</p></section>`;renderStats()}
const zones=[["campus","🏫","Grand Campus de Bellabe Adssa","Découvre ton école"],["mots","📖","Forêt des Mots","Français"],["nombres","🔢","Vallée des Nombres","Mathématiques"],["science","🧪","Île des Découvertes","Sciences"],["savoir","🌍","Continent du Savoir","Histoire & géographie"],["creative","🎨","Île Créative","Création"],["enigmes","🗝️","Tour des Énigmes","Logique"],["castle","🏰","Château de Bellabe Adssa","Grand objectif"]]; 
function map(){shell("🗺️ Carte de l'Aventure",`<p>Explore les zones débloquées grâce à tes missions.</p><div class="map">${zones.map((z,i)=>{let open=S.unlocked.includes(z[0])||z[0]==="campus";return `<div class="zone ${open?"":"locked"}"><div class="zemoji">${z[1]}</div><div style="flex:1"><b>${z[2]}</b><small>${z[3]}</small>${open?`<br><button class="btn secondary" onclick="zone('${z[0]}')">Explorer</button>`:`<br>🔒 À débloquer`}</div></div>`}).join("")}</div>`)}
function zone(id){if(id==="mots")return mission();const found=zones.find(z=>z[0]===id);shell(found?found[1]+" "+found[2]:"Zone",`<section class="card"><div class="big">${found?.[1]||"✨"}</div><h3>${found?.[2]||"Nouvelle zone"}</h3><p>${found?.[3]||""}</p><div class="notice">Cette zone évoluera avec de nouvelles missions, personnages et défis.</div><button class="btn primary" onclick="go('games')">🎮 Jouer à un mini-jeu</button></section>`)}
window.zone=zone;
function mission(){shell("📚 Mission 1 — Le premier jour",`<section class="card"><h3>Bienvenue au Campus !</h3><p>Twesy te propose une première mission : réponds à 3 questions pour gagner tes premières récompenses.</p><div id="missionBox"></div></section>`);quizMission()}
function quizMission(){const qs=[["Quel mot désigne l'endroit où l'on emprunte des livres ?","Bibliothèque",["Bibliothèque","Laboratoire","Cantine"]],["Combien font 7 + 5 ?","12",["10","12","14"]],["Quelle planète est surnommée la planète rouge ?","Mars",["Vénus","Mars","Jupiter"]]];let i=0,score=0;const box=document.getElementById("missionBox");function q(){let x=qs[i];box.innerHTML=`<div class="question">${i+1}/3 — ${x[0]}</div><div class="answers">${x[2].map(a=>`<button class="answer" onclick="this.disabled=true;missionAns(${JSON.stringify(a)},${JSON.stringify(x[1])})">${a}</button>`).join("")}</div>`;window.missionAns=(a,c)=>{document.querySelectorAll(".answer").forEach(b=>b.disabled=true);if(a===c){score++;toast("✅ Bonne réponse !")}else toast("💡 Pas grave, on continue !");setTimeout(()=>{i++;i<qs.length?q():finish()},500)}; }function finish(){box.innerHTML=`<div class="reward">🎉 Mission terminée !<br><b>${score}/3</b><br><button class="btn primary" onclick="finishMission()">Réclamer la récompense</button></div>`}window.finishMission=()=>{if(!S.completed.includes("mission1")){S.completed.push("mission1");S.unlocked.push("nombres");reward(50,20,"Premier Pas")}else toast("Mission déjà récompensée !");go("map")};q()}
function games(){shell("🎮 Mini-jeux",`<div class="grid"><button class="tile" onclick="numberGame()"><span class="emoji">🔢</span><b>Course des Nombres</b><p>Calculs rapides</p></button><button class="tile" onclick="wordGame()"><span class="emoji">🔤</span><b>Mot Mystère</b><p>Devine le mot</p></button><button class="tile" onclick="detectiveGame()"><span class="emoji">🕵️</span><b>Mission Détective</b><p>Choisis le bon indice</p></button><button class="tile" onclick="memoryGame()"><span class="emoji">🧠</span><b>Tour de la Mémoire</b><p>Retrouve les paires</p></button><button class="tile" onclick="scienceGame()"><span class="emoji">🧪</span><b>Laboratoire</b><p>Questions scientifiques</p></button><button class="tile" onclick="creativeGame()"><span class="emoji">🎨</span><b>Atelier Créatif</b><p>Crée une suite</p></button></div>`)}
function finishGame(){S.games++;reward(20,5);toast("🎮 Partie terminée !");setTimeout(games,700)}
function numberGame(){let a=Math.floor(Math.random()*9)+2,b=Math.floor(Math.random()*9)+2,op=Math.random()<.5?"+":"×",ans=op==="+"?a+b:a*b;shell("🔢 Course des Nombres",`<div class="card game-area"><div class="number">${a} ${op} ${b} = ?</div><input id="ans" class="input" type="number" inputmode="numeric" placeholder="Ta réponse"><button class="btn primary" onclick="checkNumber(${ans})">Valider</button><button class="btn secondary" onclick="numberGame()">Nouvelle question</button></div>`);window.checkNumber=(n)=>{let v=Number(document.getElementById("ans").value);if(v===n){toast("🎉 Exact !");finishGame()}else toast("💡 Essaie encore !")}}
function wordGame(){const data=[["🐶","ANIMAL"],["📚","LIVRE"],["☀️","SOLEIL"],["🌳","ARBRE"]];let x=data[Math.floor(Math.random()*data.length)];shell("🔤 Mot Mystère",`<div class="card game-area"><div class="number">${x[0]}</div><p>Écris le mot correspondant.</p><input id="word" class="input" placeholder="Ta réponse"><button class="btn primary" onclick="checkWord('${x[1]}')">Valider</button></div>`);window.checkWord=(a)=>{if(document.getElementById("word").value.trim().toUpperCase()===a){toast("🌟 Bravo !");finishGame()}else toast("💡 Regarde bien l'indice.")}}
function detectiveGame(){shell("🕵️ Mission Détective",`<div class="card game-area"><h3>Un livre a disparu. Quel indice est le plus utile ?</h3><div class="answers"><button class="answer" onclick="detective(true)">Une empreinte près de l'étagère</button><button class="answer" onclick="detective(false)">La couleur du ciel</button><button class="answer" onclick="detective(false)">Le nombre de fenêtres</button></div></div>`);window.detective=(ok)=>ok?(toast("🔎 Excellent détective !"),finishGame()):toast("🤔 Cherche l'indice directement lié au livre.")}
function memoryGame(){const vals=["🍎","⭐","🐶","🌈","🍎","⭐","🐶","🌈"].sort(()=>Math.random()-.5);let first=null,lock=false,found=0; shell("🧠 Tour de la Mémoire",`<p>Retourne les cartes et retrouve les paires.</p><div class="memory-grid" id="mem">${vals.map((v,i)=>`<button class="memory-card" id="m${i}" onclick="flipMem(${i})">?</button>`).join("")}</div>`);window.flipMem=(i)=>{if(lock)return;let e=document.getElementById("m"+i);if(e.classList.contains("open"))return;e.textContent=vals[i];e.classList.add("open");if(first===null){first=i}else{if(vals[first]===vals[i]){found++;first=null;if(found===4)finishGame()}else{lock=true;let old=first;first=null;setTimeout(()=>{document.getElementById("m"+old).textContent="?";document.getElementById("m"+old).classList.remove("open");e.textContent="?";e.classList.remove("open");lock=false},650)}}}}
function scienceGame(){const qs=[["L'eau gèle à quelle température ?","0 °C",["0 °C","50 °C","100 °C"]],["Quel organe nous permet principalement de respirer ?","Poumons",["Cœur","Poumons","Estomac"]]];let q=qs[Math.floor(Math.random()*qs.length)];shell("🧪 Laboratoire",`<div class="card"><div class="question">${q[0]}</div><div class="answers">${q[2].map(a=>`<button class="answer" onclick="science('${a.replaceAll("'","\\'")}','${q[1]}')">${a}</button>`).join("")}</div></div>`);window.science=(a,c)=>a===c?(toast("🧪 Expérience réussie !"),finishGame()):toast("💡 Observe bien la question.")}
function creativeGame(){shell("🎨 Atelier Créatif",`<div class="card"><h3>Complète la suite</h3><div class="number">⭐ 🌙 ⭐ 🌙 ?</div><div class="answers"><button class="answer" onclick="creative(true)">⭐</button><button class="answer" onclick="creative(false)">🌈</button><button class="answer" onclick="creative(false)">🔥</button></div></div>`);window.creative=(ok)=>ok?(toast("🎨 Très bien !"),finishGame()):toast("💡 La suite alterne deux symboles.")}
function work(){shell("📝 Mon Travail",`<section class="card"><p>Écris ton brouillon ici. L'écriture utilise un style manuscrit si disponible sur ton appareil.</p><div id="draft" class="workarea" contenteditable="true">${esc(S.draft)}</div><button class="btn success" onclick="saveDraft()">💾 Enregistrer</button><button class="btn secondary" onclick="downloadDraft()">⬇️ Télécharger .txt</button><button class="btn secondary" onclick="printWork()">🖨️ Imprimer / PDF</button></section><section class="card"><h3>🤖 Aide de Twesy</h3><p>Je peux t'expliquer une consigne ou te donner une piste. Je ne fais pas le devoir à ta place.</p><button class="btn primary" onclick="toast('💡 Commence par repérer les mots importants de la consigne.')">Donner une piste</button></section>`)}
window.saveDraft=()=>{S.draft=document.getElementById("draft").innerText;save();toast("💾 Brouillon enregistré !")};
window.downloadDraft=()=>{const text=document.getElementById("draft").innerText;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));a.download="mon-travail.txt";a.click();URL.revokeObjectURL(a.href)};
window.printWork=()=>window.print();
function profile(){shell("👤 Mon Profil",`<section class="card"><div class="avatar">${S.avatar}</div><h3>Niveau ${S.level} — ${esc(S.name)}</h3><p>⭐ ${S.xp} XP · 🪙 ${S.coins} pièces · 🎮 ${S.games} parties</p><div class="progress"><i style="width:${(S.xp%200)/2}%"></i></div><h3>Choisis ton avatar</h3><div class="avatar-list">${["🧑🏿‍🎓","👩🏾‍🔬","🧑🏽‍🚀","👨🏿‍🎨","🧑🏻‍🏫","👩🏽‍🚀"].map(a=>`<button class="avatar-pick ${a===S.avatar?"sel":""}" onclick="pickAvatar('${a}')">${a}</button>`).join("")}</div><h3>🏅 Badges</h3>${S.badges.length?S.badges.map(b=>`<span class="badge">🏅 ${esc(b)}</span>`).join(""):"<p>Continue l'aventure pour gagner tes premiers badges.</p>"}<hr><button class="btn danger" onclick="resetGame()">Réinitialiser la progression</button></section>`);window.pickAvatar=(a)=>{S.avatar=a;save();profile();toast("✨ Avatar modifié !")};window.resetGame=()=>{if(confirm("Réinitialiser toute la progression ?")){localStorage.removeItem(KEY);S=load();home()}}}
function welcome(){if(!S.welcome)return;S.welcome=false;save();const m=document.createElement("div");m.className="modal";m.innerHTML=`<div class="card"><div class="big">🎓✨</div><h2>Bienvenue !</h2><p>Tu es prêt à commencer ton aventure scolaire ? Twesy sera ton compagnon.</p><button class="btn primary" onclick="this.closest('.modal').remove();go('mission')">🚀 Commencer</button></div>`;document.body.appendChild(m)}
renderStats();home();welcome();
if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(()=>{});
})();